version: "3"

services:
  vpn_client:
    image: vpn_image
    container_name: client-10.0.7.5
    tty: true
    cap_add:
      - ALL
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - .:/volumes
    networks:
      net-10.0.7.0:
        ipv4_address: 10.0.7.5
    command: bash -c "tail -f /dev/null"

  host1:
    image: vpn_image
    container_name: host-10.0.8.5
    tty: true
    cap_add:
      - ALL
    networks:
      net-10.0.8.0:
        ipv4_address: 10.0.8.5
    command: bash -c "ip route del default  && ip route add default via 10.0.8.11 && tail -f /dev/null"

  host2:
    image: vpn_image
    container_name: host-10.0.8.6
    tty: true
    cap_add:
      - ALL
    networks:
      net-10.0.8.0:
        ipv4_address: 10.0.8.6
    command: bash -c "ip route del default  && ip route add default via 10.0.8.11 && tail -f /dev/null"

  router:
    image: vpn_image
    container_name: server-router
    tty: true
    cap_add:
      - ALL
    devices:
      - "/dev/net/tun:/dev/net/tun"
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - .:/volumes
    networks:
      net-10.0.7.0:
        ipv4_address: 10.0.7.11
      net-10.0.8.0:
        ipv4_address: 10.0.8.11
    command: bash -c "ip route del default  && ip route add default via 10.0.7.1 && tail -f /dev/null"

networks:
  net-10.0.7.0:
    name: net-10.0.7.0
    ipam:
      config:
        - subnet: 10.0.7.0/24

  net-10.0.8.0:
    name: net-10.0.8.0
    ipam:
      config:
        - subnet: 10.0.8.0/24
